### ISSUE TITLE
wget missing URl

### ISSUE THREAD

**Issue by bredk29** [caseyfw/nhldl#4]
getting an error when trying to run on OS X Mavericks. when running the command followed by the link to the master m3u8 file in quotes, i then get >>>fetching master m3u8 file: the link i put. then wget: missing URL Usage: Wget [Option]... [URL...] 
try 'Wget --help" for more options.
>>>done
and the terminal session holds there until i escape.

I do have my cookies.txt file in the same folder as the nhldl.sh, but it seems the script isn't getting to that. 

what am i missing?

**Comment by caseyfw** [comment]
Hmmm, not sure sorry. Can you paste the complete terminal output in here? Feel free to obfuscate the m3u8 URL just in case any of those numbers in it can be used to identify you...

**Comment by bredk29** [comment]
i gave up and downloaded ubuntu and loaded it into a virtual, after messing with it some more i discovered that the link i was presented with in my networking tab ended in .m3u8ht. once i changed that to the correct .m3u8 i was able to get it to work as expected. :)
