### ISSUE TITLE
Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by jaybrueder** [caseyfw/nhldl#8]
Hi!

First of all, I love that we cut out ads automatically now. However, for the last week or so I am getting an error whenever I download a game. It looks like this:

```
>>> Downloading stream segment: 05/16/55.ts [3220/    3220]
>>> Done.
>>> Decrypting segment.
>>> Done.
>>> Concatenating stream.
>>> Stripping blanked-out ads.
Output file #0 does not contain any stream
>>> Finished. You can now delete the NHL_GAME_VIDEO_PHILAK_M2_NATIONAL_20171006_1507050206420 directory.
```

The concatenated file will ne be copied outside the game directory.
There will be a `concatenated.mp4` file inside the game directory and this file plays just fine.
However, the ads will still be in there.

So I guess there seems to be a problem with stripping out the ads.
During that process something goes wrong and the process stops.
Therefore, not actually cutting out the ads and copying the file outside the game directory.

Anyone else observing this?

**Comment by caseyfw** [comment]
Huh, weird! I'm not seeing this issue on my Linux box - what OS are you using?

**Comment by jaybrueder** [comment]
I was also thinking that it might be an OS thing.

I am using MacOSX 10.12.6

**Comment by jaybrueder** [comment]
I am using `ffmpeg version 3.3.2`

**Comment by caseyfw** [comment]
The Mac and Ubuntu versions of bash differ, I'll try downloading today with my Mac and see how it goes.

**Comment by jaybrueder** [comment]
Ok, today it worked without a problem. Maybe I just had a glitch with one of the streams.

**Comment by caseyfw** [comment]
Hmmm, I suspect what happened was the stream (when you initially downloaded it) had not yet had the ads in it blanked out and replaced with the NHL logo. This would result in an empty list of quiet bits in `silence.txt`, and cause the ad stripping part to fail. I might add some conditionals to check to see if there are actually any silent bits before tring to strip them.

Thanks for the bug report!
